import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Logo } from "@/components/subtrack/Logo";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export const Route = createFileRoute("/reset-password")({ head: () => ({ meta: [{ title: "Choose new password — SubTrack" }, { name: "description", content: "Set a new password for your SubTrack account." }, { property: "og:title", content: "Choose new password — SubTrack" }, { property: "og:description", content: "Set a new SubTrack password." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: ResetPassword });
function ResetPassword() { const navigate = useNavigate(); const [password, setPassword] = useState(""); const [valid, setValid] = useState(false); const [message, setMessage] = useState(""); useEffect(() => { const hash = new URLSearchParams(window.location.hash.slice(1)); setValid(hash.get("type") === "recovery" || hash.has("access_token")); }, []); async function submit(event: React.FormEvent) { event.preventDefault(); if (password.length < 8 || password.length > 72) { setMessage("Use between 8 and 72 characters."); return; } const { error } = await supabase.auth.updateUser({ password }); if (error) setMessage(error.message); else void navigate({ to: "/dashboard" }); } return <main className="flex min-h-screen items-center justify-center bg-background px-5"><div className="w-full max-w-md animate-fade-up"><Logo /><h1 className="mt-10 text-3xl font-bold">Choose a new password</h1><p className="mt-2 text-muted-foreground">Create a strong password you haven’t used before.</p>{valid ? <form onSubmit={submit} className="mt-7 space-y-4"><div><Label htmlFor="new-password">New password</Label><Input id="new-password" type="password" minLength={8} maxLength={72} value={password} onChange={(event) => setPassword(event.target.value)} className="mt-1.5 h-11" required /></div>{message && <p className="text-sm text-destructive">{message}</p>}<Button className="h-11 w-full">Update password</Button></form> : <p className="mt-7 text-sm text-destructive">This reset link is invalid or expired. Request a new one from the sign-in page.</p>}</div></main>; }